Comment and receipt
cgavir29/droppy pull request #9
Opened 2020-03-07 19:37 UTC by ksgomezp

Adding functions of comment

2020-03-07 19:56 UTC, cgavir29 requested changes
La ruta para borrar no debe ser '/comment/delete/{id}'.
Si la ruta es no es vacía no debe empezar con '/'.
Parametro debe ser '{commentId}

2020-03-07 20:03 UTC, cgavir29 requested changes
Mala indentación de los métodos, los nombres de los métodos dentro del controlador no se llaman así. Revisar [guidelines](https://github.com/cgavir29/droppy/tree/master/guidelines)

2020-03-10 02:27 UTC, ksgomezp commented
Resuletos problemas de merge

2020-03-10 13:19 UTC, cgavir29 approved these changes
OK

2020-03-10 13:19 UTC, merged